### ISSUE TITLE
Feature 1: User can search for movie by title

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to type in the search bar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Typing a movie title in the search bar and clicking on the search icon will query the API to find matches.

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="379" alt="Screen Shot 2022-06-07 at 7 27 19 PM" src="https://user-images.githubusercontent.com/68703339/172518117-56bec1ae-4944-4709-a48f-b5fc42dd901f.png">
<img width="353" alt="Screen Shot 2022-06-07 at 7 27 57 PM" src="https://user-images.githubusercontent.com/68703339/172518160-d72bb7fd-8835-4506-a3e3-5c497a6ae8ec.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a background image.
- [x] Create Navbar -
   - [x] Make Navbar in a fixed position
   - [x] Make WatchFlix link to homepage
   - [x] Make MyWatchlist link to another page for users watchlist
- [x] Create a search bar -
   - [x] Make input field required
   - [x] Style input field when focused
   - [x] Add search icon to search bar
- [x] Listen for submit events on search form -
   - [x] Put the search form's input value into your data model new object
   - [x] Add the imdID, Poster, Title, Year values for each search result to the data model.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
