### ISSUE TITLE
Feature 2: User can see search results

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see search results.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user submits their search, a list of movie posters will populate if the API can pick up on their search.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="378" alt="Screen Shot 2022-06-07 at 7 34 33 PM" src="https://user-images.githubusercontent.com/68703339/172518897-4cc09ec0-e878-4ddd-839a-0e0908774a12.png">
<img width="351" alt="Screen Shot 2022-06-07 at 7 35 03 PM" src="https://user-images.githubusercontent.com/68703339/172518959-989f17d2-7d96-44ac-92c1-152ae1c1d823.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add sibling div[data-view="search-results"] to the HTML
- [ ] Define a function that switches views between home and search results
- [ ] Add a 'p' element that will have a message based on either the error or success of the search
- [ ] Add an unordered list to div[data-view="search-results"] element with dummy search results and style them to match the wireframe
- [ ] Ensure that submitting a search appends the search results to the DOM
- [ ] Ensure that refreshing the pages shows the same view as before refreshing
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the feature's functionality.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
