### ISSUE TITLE
Feature 3: User can add movie to watchlist

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add movies to their watchlist.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the search-results-view, clicking the Details button will render the movie information card (poster, title, year, plot, director, & cast). Clicking the plus icon will add a movie to your watchlist turning that icon into a check icon. Clicking the check icon will reverse the process. Clicking the back arrow will return you to your search-results-view.

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="752" alt="Screen Shot 2022-06-07 at 7 44 17 PM" src="https://user-images.githubusercontent.com/68703339/172520471-36e6b34c-ca30-4a3a-b439-0b5ccb516dba.png"><img width="352" alt="Screen Shot 2022-06-07 at 7 44 40 PM" src="https://user-images.githubusercontent.com/68703339/172520520-70be2201-76cd-444d-b244-d53aeca52172.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Listen for click events on the movie0card0info-container that will switch views to movie-info
- [ ] Ensure that clicking on movie-card-info-icon or movie-card-info-text will grab the closest data-movie-id and save it to data.selectedMovieId
- [ ] Create a function that will query the API with the data.selectedMovieId
- [ ] Ensure the API query results are appended to the DOM
- [ ] Create a function that will add a movie to the data.watchlist when clicking on .info-card-nav-add icon.
- [ ] Ensure that clicking the info-card-nav-back icon goes back to the previous screen.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
