### ISSUE TITLE
Feature 4: User can view their watchlist

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view watchlist.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking on Your Watchlist, it will render the movies added to the user's watchlist. If no movies are on the watchlist there will be a message saying the watchlist is empty.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="752" alt="Screen Shot 2022-06-07 at 7 56 06 PM" src="https://user-images.githubusercontent.com/68703339/172521844-90e59d4b-06d8-4864-83a4-c9b4ed8adcdd.png">
<img width="351" alt="Screen Shot 2022-06-07 at 7 55 40 PM" src="https://user-images.githubusercontent.com/68703339/172521862-939ecd85-bed1-4893-9b59-409de209013e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add sibling div[data-view="watchlist"] to the HTML
- [ ] Listen for click events on the .watchlist element that will switch page view to watchlist
- [ ] Create a function that searches data.watchlist and appends the appropriate message and movies to the watchlist view
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the feature's functionality.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
