### ISSUE TITLE
Feature 5: User can remove movie from watchlist

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can remove movies from the watchlist
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the watchlist-view, clicking the Details button will render the movie information card (poster, title, year, plot, director, & cast). Clicking the check icon will remove a movie from your watchlist turning that icon into a plus icon. Clicking the plus icon will reverse the process. Clicking the back arrow will return you to your watchlist-view.

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="755" alt="Screen Shot 2022-06-07 at 8 03 50 PM" src="https://user-images.githubusercontent.com/68703339/172522750-87b86cc3-fa1e-4996-a4ee-0a56413bab32.png">
<img width="753" alt="Screen Shot 2022-06-07 at 8 04 08 PM" src="https://user-images.githubusercontent.com/68703339/172522769-49d00089-69fe-489a-a7b7-c8a19ff9e39b.png">
<img width="753" alt="Screen Shot 2022-06-07 at 8 04 20 PM" src="https://user-images.githubusercontent.com/68703339/172522788-4a6c1566-aa6c-4b08-a0df-09a6370b482d.png">

<img width="351" alt="Screen Shot 2022-06-07 at 8 05 23 PM" src="https://user-images.githubusercontent.com/68703339/172522941-53acff65-7107-479c-b125-fb4ec50b816d.png">
<img width="351" alt="Screen Shot 2022-06-07 at 8 05 40 PM" src="https://user-images.githubusercontent.com/68703339/172522970-da4a6ce2-b5cc-4cad-bbfa-a7050959b12f.png">
<img width="352" alt="Screen Shot 2022-06-07 at 8 05 50 PM" src="https://user-images.githubusercontent.com/68703339/172522985-833b51d8-f3eb-40b8-9157-c5682e17841e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Ensure that clicking on .info-card-nav-add-remove icon will remove a movie from the data.watchlist and the .watchlist-movie-cards-container
- [ ] Ensure that clicking the info-card-nav-back icon goes back to the previous screen
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
